### PR TITLE
Add convenience function RichEmbed.addBlankField

### PR DESCRIPTION
**Pull request by Slamakans**

### CODE REVIEW

**Comment by appellation** [comment]
It might also be worthwhile to change `setDescription`'s parameter optional and automatically fill it with `\u200b` if omitted.

**Comment by PgBiel** [comment]
^

**Comment by bdistin** [comment]
I originally had a feature like this with a RichEmbed PR I made, for which I was told to remove from my pr. I doubt this will be allowed to be added, from my experience.

**Comment by Slamakans** [comment]
@appellation Making a blank inline field would still require you to type out the entire thing though.
Would be cool if default params worked like python kwargs, but without all the hassle when you don't want to use the keyword for it.

**Comment by Slamakans** [comment]
@bdistin Yeah :thinking:

**Comment by GusCaplan** [comment]
a sad sad day is upon us...

**Comment by Slamakans** [comment]
@GusCaplan Hahahahah

**Pull request merged**
