### PR TITLE
Add voiceChannel property to User.

### PR DESCRIPTION
**Pull request by cpancake**
I added a voiceChannel property to user which contains the voice channel that the user is currently in, or null if they're not in a voice channel, as per #106.

I also added a userVoiceUpdate event which is emitted when a user joins or leaves a voice channel.

### CODE REVIEW

**Comment by abalabahaha** [comment]
Voice channels are typically tied to guild (memberMap + detailsOf)

**Comment by cpancake** [comment]
I'm not quite sure what you're saying, sorry. Are you saying that I should instead make a function to get the voice channel of a user on the server object?

**Comment by abalabahaha** [comment]
https://github.com/hydrabolt/discord.js/blob/master/src/Structures/Server.js#L34
https://github.com/hydrabolt/discord.js/blob/master/src/Structures/Server.js#L74

IMO something like memberMap would be a better place to store the user's voice channel.

**Comment by cpancake** [comment]
How's this?

I also fixed a few issues with file volume. The order of the arguments meant that the filter was ignored, and the short circuiting meant that a volume of "0" would result in a volume of "1".

**Comment by TehSeph** [comment]
Might also want to supply the server as part of the event. :)

Also, next time you make a PR you shouldn't include things that aren't relative (in this case, the volume change) and make another PR for any additional changes you want to make.

**Comment by cpancake** [comment]
The server can be accessed through channel.server, so I'm not sure if I should add it as a parameter. And I included the volume change because I don't think (might be wrong) that there's a way to make two PRs at the same time.

**Comment by TehSeph** [comment]
1) True, but since it's included in the data of the packet, it's nice to pass along to the event.
2) You can, you just need to make a new branch. :)

**Comment by hydrabolt** [comment]
This is already being worked on in the indev branch so unfortunately I see no reason to accept the PR, however thanks anyway

**Pull request closed without merging**
