### PR TITLE
Permissions Cleanup

### PR DESCRIPTION
**Pull request by bdistin**
**Please describe the changes this PR makes and why it should be merged:**
Cleans up permissions in d.js:

- Permissions class:
  - BreakingChange: ~~add and remove no longer return new instances, but instead return the modified instance. (add and remove did not work as advertised before this pr, as member is not a valid param of Permissions anymore)~~ add and remove return new instances if the instance is frozen. Modifies the instance if not.
  - BugFix: 0 is a valid permission.
  - Cleanup: several small tweaks for optimization (reverse for loops, order of Permissions.resolve())
  - Added: Permissions.freeze to return immutable instances of the class. (all returned permissions changed to frozen permissions)
  - Added: Permissions as a possible PermissionResolveable, cleaned up instances where using the bitfield prop, instead of the permissions instance itself.
  - BugFix: RangeError('PERMISSION_INVALID') is an invalid error message key, it is corrected to PERMISSINS_INVALID.

- PermissionOverwrites class:
  - BreakingChange: removed this._denied and this._allowed in favor of this.allowed.bitfield and this.denied.bitfield as the data was double stored.
- Guild class:
  - ~~BugFix: overwrite.allow/overwrite.deny aren't a thing since: 1e47cfdd5df1654ac6ed47146e09f34e3e49b0c5.~~ Reverted as this is meant for `[{allow:1, deny:1}]` to be passed instead.

- GuildChannel class:
  - Cleanup: cleaned up permissionsFor and overwritesPermissions
  - BugFix: return new Permissions(Permissions.all) if the member has administrator earlier. (fixes if discord says Adminstrator deny as an overwrite)

- GuildMember class:
  - Cleanup: get permissions()
  - BugFix: missing permissions was trying to use the param permissions, as if it were an instance of Permissions; instead of this.permissions.

- Role class:
  - BreakingChange: role.permisions now returns a frozen instance of Permissions.
  - Cleanup: permissions usage to use the permissions instance.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
This does not include previously PRed channel.permissionsFor(Role) or role.permissionsIn(channel); however it does include the bugfixes from that PR.

**Comment by Gawdl3y** [comment]
Not a fan of the add/remove changes - the object is supposed to be immutable, just like an Integer or String instance.

**Comment by bdistin** [comment]
Added Permissions.freeze to return immutable instances. All instances returned from the library made frozen.

Likely controversial: fixed add/remove to return a new instance of Permissions if the instance is frozen, rather than having a typeError be thrown because this.bitfield would be readOnly in the frozen instance.

**Comment by devsnek** [comment]
Can we just leave the main perm calculation alone so we can stay visually consistent with the calculation

**Pull request merged**
