### PR TITLE
Add cache limits to all stores

### PR DESCRIPTION
**Pull request by bdistin**
**Please describe the changes this PR makes and why it should be merged:**
Allows users to define cache limits for all stores. You don't wan't to cache emojis because your bot doesn't use them? `new discord.Client({ cacheLimits: { emojis: 0 } })`

This changes `client.options.messageCacheMaxSize` to `client.options.cacheLimits.messages`; where all other cache limits are set.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
this should implement LRU so that cached items that get used don't get deleted by the limits.

**Comment by hydrabolt** [comment]
This could break a lot of things and cause a lot of unintentional behaviour...

**Comment by KingDGrizzle** [comment]
_And I don't think setting all the caches to Infinity by default will be a good idea_

**Comment by KyeNormanGill** [comment]
Message caching is already unlimited by default 🤣

**Comment by KingDGrizzle** [comment]
Its not, it limits at 200 by default 😉

**Comment by KyeNormanGill** [comment]
They don't get sweeped by default so they're always cached.

**Comment by dragonfire535** [comment]
Everything except messages already essentially had Infinity as the limit. With messages by default it would cache 200 and then remove the oldest by insertion time when the amount in cache went over the limit.

**Comment by hydrabolt** [comment]
We're planning on allowing use for external stores, so I think it would be better to create your own stores for this. Discord.js data stores by default shouldn't really have limits/LRU unless they're required, because it stills incurs a performance cost.

**Pull request closed without merging**
