### PR TITLE
easy readable syntax

### PR DESCRIPTION
**Pull request by AndreiSoroka**
in my humble opinion

### CODE REVIEW

**Comment by AndreiSoroka** [comment]
test fail? really? 😄

**Comment by meew0** [comment]
This changes the functionality, now the "Logged in" message is printed even if it has failed.

**Comment by abalabahaha** [comment]
@meew0 there's a return statement

**Comment by AndreiSoroka** [comment]
Guys! What can I do?

**Comment by GusCaplan** [comment]
@AndreiSoroka read why the build failed. just click "details" on the build

**Comment by AndreiSoroka** [comment]
@GusCaplan, what is "Logging In"? I'm not understand. where login?

**Comment by Gawdl3y** [comment]
Doesn't look like anything is wrong with your code, it's just that there was an odd error during the travis build.
Regardless, this PR will be irrelevant within the next day, when v9 (rewrite) is released officially.

**Comment by hydrabolt** [comment]
This is redundant because of [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)

**Pull request closed without merging**
