### PR TITLE
Add check

### PR DESCRIPTION
**Pull request by Serhann**
**Please describe the changes this PR makes and why it should be merged:**
In order to avoid an error, we need to check that the default channel is deleted. _(translated by google translate)_

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
But `defaultChannel` doesn't exist at all anymore...?

**Comment by iDroid27210** [comment]
Yes it's completly useless because your greeting will never be executed.
There's no defaultChannel **at all** anymore, do something like a channels filter (if it's a text channel and if it has `SEND_MESSAGES` permission in).

**Comment by Serhann** [comment]
Hmm, thx guys i'm removing it.

**Comment by ArtutoGamer** [comment]
The "new" default channel is based on the first channel on the user has `MESSAGE_READ` permission.

**Comment by iCrawl** [comment]
Fixed properly in 2aa2f73c

**Pull request closed without merging**
