### PR TITLE
clyde should always be online

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by Programmix** [comment]
i should just kill myself now

**Comment by Cat-who-loves-bots** [comment]
:eyes:

**Comment by xshotD** [comment]
what's the point of this?

**Comment by GusCaplan** [comment]
keeping the easter eggs up to date is important

**Comment by Hazeral** [comment]
💯

**Comment by hydrabolt** [comment]
surely this would mean `clyde.presence == clyde.presence` would be false

**Comment by GusCaplan** [comment]
~~presence.equals~~

**Comment by GusCaplan** [comment]
😢

**Pull request closed without merging**
