### PR TITLE
fix(avatarURL): gifs not being animated

### PR DESCRIPTION
**Pull request by Lewdcario**
**Please describe the changes this PR makes and why it should be merged:**
`?size=2048` made gifs not animated. This should fix that.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by KingDGrizzle** [comment]
In a way, this fixes it. But the CDN actually supports animated guf resizing, and will animate them if the string ends with ".gif".

So, a url with ?size=2048, and a gif should end in "&.gif"

**Comment by devsnek** [comment]
this should *not* be merged. it isn't a bug with discord.js, and introduces unwanted behavior.

**Comment by appellation** [comment]
the avatar is a gif and is properly resized according to the parameter.  how various clients display it is not our issue.  gus is correct; this is not a problem with discord.js and would in fact reduce functionality.

**Comment by Lewdcario** [comment]
But we force the size on gif avatars so nobody can have gif in stable. This issue is removed in Master with the function, but it is in issue in stable..

**Comment by appellation** [comment]
stable memes FeelsBadMan

**Comment by devsnek** [comment]
tbh this is probably fine, i just saw dgrizzle had linked it as the same thing but for 11.3

**Comment by KingDGrizzle** [comment]
you mean 12.0?

**Comment by hydrabolt** [comment]
going to merge for now, if anyone has any complaints, please comment!

**Pull request merged**
