### PR TITLE
Create Royal Guard

### PR DESCRIPTION
**Pull request by CaptainKraken**
**Please describe the changes this PR makes and why it should be merged:**

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
No description.
No explanation.
Addition of a file without any of those means no merge.

**Comment by YorkAARGH** [comment]
Hmm, I'm a little more outspoken, but to use the street lingo kids use now-a-days... _wtf does this do?_

**Comment by dragonfire535** [comment]
:thinking: Is this some kind of joke

**Comment by Tvde1** [comment]
Yeah this is definitely some troll.

**Pull request closed without merging**
