### PR TITLE
Implementing `iconURL` method in `PartialGuild`

### PR DESCRIPTION
**Pull request by iDroid27210**
**Please describe the changes this PR makes and why it should be merged:**

• Adding `iconURL` method from `Guild` in `PartialGuild` to make the task easier (we must do `https://cdn.discordapp.com/icons/<Guild ID>/<Guild icon>.<format>?size=<size>` currently).

• It should be merged because there's no reason for why it shouldn't be, it would make the dev life easier and clean the code and it can't make conflict with other things.

**Semantic versioning classification:**  
- [X] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iDroid27210** [comment]
lmao I put the method in setup accidentaly, lemme fix

**Comment by devsnek** [comment]
tbh i'm planning to drop the partial guild object, this change might go wasted.

**Comment by iDroid27210** [comment]
What would replace it ? It would go in the normal Guild object ?

**Comment by devsnek** [comment]
ya

**Pull request closed without merging**
