### PR TITLE
fixed little mistake in docs of createGuild

### PR DESCRIPTION
**Pull request by Dev-Yukine**
**Please describe the changes this PR makes and why it should be merged:**
bots can also create servers but must be in 10 or less servers in total

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by professor-cat** [comment]
This should be used only for game bridge not everyday with bots creating guilds so docs shouldn’t mention this

**Comment by Dev-Yukine** [comment]
I still think Docs should mentions this because Discord.js does "100%" cover the Discord api and implements a lot of stuff peeps should not use but its there for coverage.

**Comment by HorizonTM** [comment]
dab

**Comment by professor-cat** [comment]
@Dev-Yukine As said before this was only intended to be for game bridge usage (can change in future) and discord already provides sdk which uses this.

By also letting people know about this they could potentially abuse it by mass creating guilds, not to mention they can have more than one application that can take advantage of this for parallel abusing.

**Comment by YorkAARGH** [comment]
@professor-cat this has been public knowledge for some time now (at least most of 2017), and you cannot abuse it, because as soon as your bot hit's 10 guilds you lose the functionality.

**Comment by Dev-Yukine** [comment]
@professor-cat exactly like York said it lose the functionality after 10+ guilds aswell as you can only have up to 9 Applications (i think) what would be 90 guilds created via bots and it has also a ratelimit, so i dont think it will be abused and can't be abused really since its limited to 10 guilds per Bot and 9 Bots per User account

**Comment by devsnek** [comment]
this pr is incorrect, and a lot of the comments are wrong too. what would be nice is removing the info block entirely, as it isn't correct.

**Comment by Dev-Yukine** [comment]
for everyone who is asking why i removed it now

**Comment by GetRektByMe** [comment]
Assuming they have full functionality is rather stupid. Assumptions is just going to lead to dumb questions in the support channel. Considering the default is that there is a limit, surely this should be mentioned briefly in the documentation.

**Comment by devsnek** [comment]
it isn't our job to document how discord works, its to document how discord.js works.

**Comment by GetRektByMe** [comment]
The library is based on Discord's API, so the limits are imposed onto the library by the API. If you don't document the API at all then you can't document the library well.

**Comment by appellation** [comment]
I feel like the Discord API docs should document the Discord API and the Discord.js docs should document Discord.js. Library documentation is intended to describe how that library interacts with the underlying service, not anything specific to the service.

**Comment by GetRektByMe** [comment]
Yes and it will have restrictions on how it will interact with the API depending on how the underlying API works, there is an overlap between the two, which is why you should mention it in the documentation.

**Comment by Dev-Yukine** [comment]
The thing is that recchan is still correct tho, people will think they can create Guilds with there bots even if these people aren't whitelisted and on more than 10 guilds and if its not working come to the Discord server and ask "why its not workin" so idk there should be a note somewhere that atleast briefly mentions that.

**Comment by Dev-Yukine** [comment]
seems like this PR is dead and wont be accepted due several reasons, that means i will close this PR now.

**Pull request closed without merging**
