### PR TITLE
VoiceManager reject on error

### PR DESCRIPTION
**Pull request by telunc**
Fix unhandled event error for VoiceManager. This manager calls VoiceConnection, but did not handle the reject event. Causing programs to crash.

This pull request handles the crash in #1595 . And will properly handles the catch event.

**Catch will never be console logged**
```js
// Join a voice channel
voiceChannel.join()
 .then(connection => console.log('Connected!'))
 .catch(console.error);
```

### CODE REVIEW

**Comment by aemino** [comment]
What's this PR really doing? By the time the time an error event would be fired, the VoiceConnection would have already authenticated and the joinChannel function would have resolved. There isn't a "crash" in #1595 but rather an unhandled error.

Here's the basic event flow.
First, joinChannel is invoked. Next, a VoiceConnection is instantiated/constructed.  After that, the VoiceConnection immediately calls `authenticate()`. At this point in time, the state of the VoiceConnection is `AUTHENTICATING`. During the `authenticate()` method, a timeout is started to allow 15 seconds for the VoiceConnection to connect.  If the VoiceConnection manages to authenticate within this timeframe, there were no errors and the timeout will be cleared.  If, at this point in time, the VoiceConnection has not successfully initiated a connection, an error will be thrown.  The error is passed to `authenticateFailed()`.  Since at this point in time, the VoiceConnection's status would still be `AUTHENTICATING`, the error would be passed up as a `failed` event.  Therefore, it would be caught.

**Comment by telunc** [comment]
Yeah. It's an unhandled event that should have been handled. #1595 exited with `status 1`. Error was never catched by the `.catch(console.log);`

```js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! musicbot@1.0.0 start: `node --optimize_for_size src/main.js`
npm ERR! Exit status 1
```

**Comment by iCrawl** [comment]
@telunc did you even read what he said?

**Comment by telunc** [comment]
@iCrawl Yes, I did. He was explaining the event flow and how come it was supposed to be caught. It's easy to see some bug occurred along the way since the event was never passed to `failed` event. If it were handled properly, issue #1595 would have been caught by the `catch` statement instead of exiting with a `status 1`.

**Comment by aemino** [comment]
My point is that, regardless of whether or not the error is being caught, it shouldn't be possible for `error` to be thrown while still authenticating, which is what this issue deals with.  If `error` *can* be thrown during authentication, this is a different bug that needs to be addressed.

**Comment by telunc** [comment]
I hope this bug will be resolved soon. This PR tackled the problem instead of implementation. It's currently crashing every program that fails to join a voice connection. Hopefully this PR will be merged or a better solution come up.

**Comment by hydrabolt** [comment]
Can you see if the above PR fixed your issue? Thanks.

**Comment by iCrawl** [comment]
Since there are no further comments on the subject I see this as resolved.

Adding to that aemino is currently working on a rewrite of the Audio section in v12.

**Pull request closed without merging**
