### PR TITLE
make use of qs instead of manually building querystring

### PR DESCRIPTION
**Pull request by SimonSchick**
promise simplification and optimisation
use Array.map instead of forEach for mapping
added missing rethrows
emit error events in typing
removed unusued EventEmitter import
no braces for single arg arrow function
added missing semicolons

### CODE REVIEW

**Comment by TehSeph** [comment]
Image of Github being retarded
glhf @hydrabolt

**Comment by abalabahaha** [comment]
^

**Comment by SimonSchick** [comment]
There was tons of duplicate code(in almost every function), the amount of changes is a result of that.

**Comment by abalabahaha** [comment]
ayy betatesters report errors thanks

**Pull request merged**
