### PR TITLE
Add Two-Factor Authentication support

### PR DESCRIPTION
**Pull request by GexoXYZ**
This is just a suggestion on how it could be done. It works for me but it might have some trouble with already existing cached tokens ?

### CODE REVIEW

**Comment by abalabahaha** [comment]
Not exactly fun to edit a new code in every time the cache is cleared... loginWithToken would be better for 2FA accounts

**Comment by alfw** [comment]
Woldent it be better to add in a new function instad of expanding on the login() for not breaking for older code? example add it in as login2fa(user,pw, 2fa, callback) ?

**Comment by GexoXYZ** [comment]
I'm just gonna push what abal says is the way to go.

**Comment by GexoXYZ** [comment]
@abalabahaha how exactly would I implement this in loginWithToken? Since no token is supplied before  `POST`ing the code
```js
{ mfa: true,
  token: null,
  ticket: 'WzEsdfMDc4MzA3NjfefefyxcvasddfgadfgQ.CjXsyxccve2xwpkJd0ydfasdweasfsdf7knE5ZzE' }
//POST THE CODE WITH THE TOKEN

{ token: 'test.6IWseIHjyFSDFSF5BN98Ad-K5fsdfweqweyLKfysdfsfsfereSyyuNe2LkVc6XJKqe2CTGNMrdasdMzKyDFMWhv8yk5' }
```

**Comment by abalabahaha** [comment]
The user can just supply the 2FA token...

**Comment by GexoXYZ** [comment]
Jake said no anyways

**Pull request closed without merging**
