### PR TITLE
[WIP] add toJSON methods to things

### PR DESCRIPTION
**Pull request by devsnek**
**Please describe the changes this PR makes and why it should be merged:**
stringifying stuff is a thing that happens, this makes it easier

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
The method name toJSON seems misleading. You are providing a JavaScript Object, not JavaScript Object Notation (JSON strings).

I assume the point of this is to remove circular references, so it is easier to commit directly to no-sql databases?

I don't really have a clean alternative to toJSON, at-least without knowing for sure the intended use.

**Comment by devsnek** [comment]
@bdistin the toJSON method is used by JSON.stringify. If you have a problem with it talk to tc39

**Comment by bdistin** [comment]
Ok, I misunderstood the idea of this pr. This is like how we overwrite the toString() of certain objects. So when we do `JSON.stringify(discordUserInstance)` it uses the object that is generated from toJSON()....

**Comment by devsnek** [comment]
closing for #1859

**Pull request closed without merging**
