### PR TITLE
Added position parameter to channel.clone() - closes #1216

### LINKED ISSUE #1216: channel.clone() - position parameter
hey,

can there be a position parameter be added to the channel.clone() method?

### PR DESCRIPTION
**Pull request by Sir-Will**

### CODE REVIEW

**Comment by Programmix** [comment]
I disagree with this change being implemented. If we are to implement position, who is to say that we shouldn't implement all properties into the clone method? Discord doesn't support changing channel properties as soon as the channel is created, so neither should we. The proper way to go about this is to just write your own code to handle this.

**Comment by Sir-Will** [comment]
Hm, not sure why `setTopic` was added then.

**Comment by Programmix** [comment]
Those (`withPermissions` & `withTopic`) are there because the Discord API supports them being used in the channel creation endpoint.

**Comment by Sir-Will** [comment]
https://github.com/hydrabolt/discord.js/blob/master/src/structures/GuildChannel.js#L260
Topic gets set after channel got created not in the channel creation.

Anyway, feel free to close this.

**Comment by GusCaplan** [comment]
i only added name, type, and permissions, and then this one dude decided we needed the topic, and it all went downhill from there

**Comment by Gawdl3y** [comment]
I also don't see the need for this. Adding a position parameter is modifying the channel, therefore not making it a direct clone. The topic, however, is simply cloning more data over to make up for Discord's slight deficiency there.

**Comment by mustqfqq** [comment]
.

**Pull request closed without merging**
