### PR TITLE
Corrected PM Message Documentation

### PR DESCRIPTION
**Pull request by IanMitchell**

### CODE REVIEW

**Comment by GexoXYZ** [comment]
I think this should adressed in the code rather than in the docs

**Comment by IanMitchell** [comment]
I'm fine either way; I wasn't sure what the preferred return value was, so I deferred to what the current functionality is.

**Comment by Programmix** [comment]
I wrote the documentation for this particular property and it seems to me that the general convention of the docs is to specify a parameter as 'null', even if it's really undefined.

**Comment by IanMitchell** [comment]
If I encounter it elsewhere, I'll fix it there too. But as is, this is incorrect and should be updated

**Pull request merged**
