### PR TITLE
Docs Missing Deny and Allow for PermissionOverwrites

### PR DESCRIPTION
**Pull request by FireController1847**
**Please describe the changes this PR makes and why it should be merged:**
The docs are missing for PermissionOverwrites allow and deny property.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
Pretty sure those are chosen to be undocumented. And if anything they should probably be documented as private.

**Comment by FireController1847** [comment]
@iCrawl Why would they be private/undocumented? It seems that people use them, should they not know of their existance? lol

**Comment by iCrawl** [comment]
There's usually always a very good reason certain things are not public API.

**Comment by devsnek** [comment]
they are private because we don't want people do overwrite them and fuck things up

**Comment by FireController1847** [comment]
@devsnek Then could we not just do @readonly or something of the sort? I mean, if nobody knows about it why implement it at all?

**Comment by iCrawl** [comment]
You clearly have no idea of how this works Fire.

If something isn't documented, doesn't mean you can't use it. You just shouldn't rely on it, because we don't know if we are going to remove it or not, or what gus said.
The same concept applies to all the REST methods. You can use them, but they aren't documented.

**Comment by devsnek** [comment]
it isn't readonly, so we can't mark it readonly

**Comment by FireController1847** [comment]
Oh wow, I feel dumb. Yeah sorry. Still seems kinda important to add this though, as it would be the users fault if they fk things up?

**Comment by iCrawl** [comment]
It's always the users fault if they fuck up, but no. I don't feel like it should be in the public API.

**Pull request closed without merging**
