### PR TITLE
Permissions for(role)

### PR DESCRIPTION
**Pull request by bdistin**
**Please describe the changes this PR makes and why it should be merged:**
Allows role resolveables to be passed to <channel>permissionsFor() to check the resolved permissions for a given role after channel overwrites. (also adds a resolveRole method to the client data resolver, and cleans up a second instance where duplicate code existed)

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
- [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by xDdude** [comment]
iirc there is no typedef for RoleResolvable. There are also other instances (GuildMember role stuff) where the resolveRole method could be used for consistency.

**Comment by GusCaplan** [comment]
a shitload of code is duplicated in those the if/else can you reuse some code plz ❤️

**Comment by bdistin** [comment]
Perhaps I am missing what you are seeing? But I see no code that can be reused... Given the way permissions must be applied to resolve correctly that is.

**Comment by rei2hu** [comment]
> Perhaps I am missing what you are seeing? But I see no code that can be reused... Given the way permissions must be applied to resolve correctly that is.

I think there is always an @everyone overwrite and assuming that's true, one way to do it is the following:

1. Make an array with guild id for @everyone overwrite
2. If role is provided, push role id to array. If member is provided, push member id and role ids to array.
3. Iterate through array and do the bitwise operators.

This might be a little shorter.

**Comment by bdistin** [comment]
That is specifically what you cannot do. Permissions must be applied in a specific manner according to https://support.discordapp.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured- That was how it permissionsFor was coded before an earlier pr of mine, and it caused incorrect permission resolution in several edge cases.

**Pull request closed without merging**
