### PR TITLE
Fix inconsistencies with usage of full stops

### PR DESCRIPTION
**Pull request by Jamelele**

### CODE REVIEW

**Comment by iCrawl** [comment]
Many of those don't have full stops/periods because they are not complete sentences....

**Comment by Jamelele** [comment]
True, but it's still inconsistent. Take a look at the class summaries for these two:

- https://discord.js.org/#/docs/main/master/class/DMChannel

- https://discord.js.org/#/docs/main/master/class/Emoji

I just thought for the sake of consistency that it would be a good idea to have a full stop on all of them, but maybe this isn't a good idea.

**Comment by Programmix** [comment]
I appreciate what this commit is trying to do but you've gone about it the opposite way... stuff like this in JSDocs should **not** have periods.

**Comment by Jamelele** [comment]
I'll make a new PR to do the opposite then, would be easier to go from the start again.

**Comment by Gawdl3y** [comment]
I think methods and classes should probably have full-stops... maybe properties, too?
I'm not 100% decided, but parameters and such definitely shouldn't.

**Comment by Jamelele** [comment]
Yeah, I decided to leave the parameters out.

**Comment by Jamelele** [comment]
I'll reopen this, as I'm not quite sure how to approach this.

**Comment by Gawdl3y** [comment]
Gonna close this, as I'm planning on doing a lot of documentation cleanup/improvement soon™.

**Pull request closed without merging**
