### PR TITLE
Link npm downloads shield to npmcharts.com

### PR DESCRIPTION
**Pull request by cheapsteak**
**Please describe the changes this PR makes and why it should be merged:**

Changes the link for the "downloads" badge to link interactive download trend graph at https://npmcharts.com/compare/discord.js?minimal=true

The badge to the left already links to npmjs.com, and seeing the upwards trend would perhaps be more compelling for potential users :)

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by lloti** [comment]
lol

**Comment by PgBiel** [comment]
Why are you advertising your website on 4 different repositories?

**Comment by cheapsteak** [comment]
Feel free to close if not interested :)

**Comment by cheapsteak** [comment]
And to answer your question, I have a gaping void in my heart that can only be filled by people using stuff I make, and this seemed like a win-win ;)

**Comment by devsnek** [comment]
@cheapsteak you should make a system for badges that people can put on their pages to show download counts instead of external links

**Comment by cheapsteak** [comment]
I think the shields.io downloads badge looks great and we both pull data from npm

Both the npm and npm badge are currently also already external links. Whether it's better that they both link to the npmjs.org page, or if it would be cool to link the other one to something else?

Could be [npmcharts.com](https://npmcharts.com/compare/discord.js?minimal=true), could be [npmtrends](http://www.npmtrends.com/discord.js) (not mine, their charting currently seems to be broken but it typically isn't)

**Comment by iCrawl** [comment]
Cool site 👍 

But no, thank you!

**Pull request closed without merging**
