### PR TITLE
Feature/animated emojis

### PR DESCRIPTION
**Pull request by TrueBoxGuy**
**Please describe the changes this PR makes and why it should be merged:**
Allows animated emojis in voice-rewrite

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by TrueBoxGuy** [comment]
Should be good

**Comment by TrueBoxGuy** [comment]
Sorry, I thought this was on my fork

**Comment by TrueBoxGuy** [comment]
Should I close this?

**Comment by devsnek** [comment]
yes

**Comment by Jisagi** [comment]
Could someone push this also to master? Would be really nice to have this not only in 'voice-rewrite'.

**Comment by Dev-Yukine** [comment]
see #2182

**Comment by Jisagi** [comment]
@Dev-Yukine i see, thanks! guess i missed that one

**Pull request closed without merging**
