### PR TITLE
Added cleanContent getter 

### PR DESCRIPTION
**Pull request by LewisHogan**
(Majority of code implemented by Gus).

### CODE REVIEW

**Comment by Gawdl3y** [comment]
Looks like this will fail on invalid mentions of any kind (if someone just sends `<@424242>` in a message, for instance).

**Comment by Programmix** [comment]
I feel like this should use the mentions property of messages to calculate the clean content. This should work for users, nicknames, roles, and channels.

**Comment by macdja38** [comment]
Should this also clean @ everyone from the text? Personally I create a "clean" @ everyone by inserting a zero width space between the @ and the everyone.

**Comment by Gawdl3y** [comment]
Yeah, `@everyone` and `@here` should be "cleaned" as well by inserting a ZWS.

**Comment by Gawdl3y** [comment]
Those replaces for `@everyone` and `@here` are case-sensitive.

**Comment by macdja38** [comment]
@Gawdl3y Which makes sense considering that discord uses lower case characters for `@here` and `@everyone`.

**Comment by macdja38** [comment]
This won't work on multiple instances of either `@everyone` or `@here`. In order to function in those cases the regex /@everyone/g could be used instead. For example `.replace(/@everyone/g, '@\u200Beveryone')`. This could be made insensitive by adding the i flag after the G, though I maintain that this would be counter productive as discord itself treats these in a case sensitive manner.

**Comment by Gawdl3y** [comment]
Ah, yup, Discord only accepts lowercase anyways.

**Comment by GusCaplan** [comment]
tfw you forget that people do invalid/uncached mentions ;(

**Comment by Gawdl3y** [comment]
If you resolve the conflicts, I will merge this.

**Pull request merged**
