### PR TITLE
fixed volume option and set default to 25% to avoid hearing loss

### PR DESCRIPTION
**Pull request by macdja38**
Should fix issue #118

### CODE REVIEW

**Comment by khionu** [comment]
I installed and tested. Volume fix does not seem to be working. I set volume to `.01` and `1`, and it was identical.

**Comment by macdja38** [comment]
I have not rebuilt the /lib with grunt.

**Comment by abalabahaha** [comment]
Can someone else verify this?

**Comment by Lord-Ptolemy** [comment]
Seems to work on my end.

**Comment by khionu** [comment]
Confirmed as Partial Fix. `playFile` still does not work with the volume argument, but `playRawStream` does.

**Pull request merged**
