### PR TITLE
Init pause variable on VoiceBroadcast

### PR DESCRIPTION
**Pull request by FireController1847**
**Please describe the changes this PR makes and why it should be merged:**
Dispatchers have a way for you to check if something is paused, but it's not currently possible to check if a Broadcast is paused without any dispatchers in it and pausing it first. This just initiates the variable like a Dispatcher :P

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
It seems like initializing it to `undefined` (which is how it is currently) is roughly similar to initializing it to `false`; my point is that, while correct, this shouldn't actually change any functionality for you.

**Comment by FireController1847** [comment]
@appellation Yeah, it works fine, but it should be documented ;P

**Comment by aemino** [comment]
👨‍🌾

**Comment by iCrawl** [comment]
🌱

**Pull request merged**
