### PR TITLE
User limit fix

### PR DESCRIPTION
**Pull request by Programmix**

### CODE REVIEW

**Comment by nicholastay** [comment]
From my little bit of testing, only `name` and `user_limit` fields need to be sent...

**Comment by abalabahaha** [comment]
Forgot to reply to this, but yeah ^ I thought ^ too...

**Comment by nicholastay** [comment]
Update: `position` needs to be sent as well for it to keep the position

**Comment by abalabahaha** [comment]
_glares at hammerandchisel/discord-api-docs#28_

**Comment by Programmix** [comment]
So, could someone please give me the final judgement clarification?
1. What properties are required for text channel modifications without any consequences?
2. What properties are required for voice channel modifications without any consequences?

(Also, abal, I'm sorry for being annoying, please unblock. <3)

**Comment by nicholastay** [comment]
For voice channels, you can refer to my bitrate update commit and those
should have all the fields required right now to modify without consequence.

Should be `name`, `bitrate`, `user_limit` and `position`.

**Comment by Programmix** [comment]
All right, I pushed new commits. Hopefully they address the previous issues.
For methods that are used for both text and voice channels, I just send all parameters for both. Some may be undefined, but it still works as intended.

**Comment by nicholastay** [comment]
Instead of making this many functions for each update thing, I feel like there should be just a centralized `.updateChannelDetails()`, where an object can be passed with any of these details (optionally) and that would be cleaner if someone wanted to update more than one detail at a time.

**Comment by abalabahaha** [comment]
I added #367 for that

**Pull request merged**
