### PR TITLE
create ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by MrSakamoto-san**
less people with useless issues

### CODE REVIEW

**Comment by GusCaplan** [comment]
don't hardcode the version, tell them to check package.json in master

**Comment by GusCaplan** [comment]
why are there html comments in this

**Comment by MrSakamoto-san** [comment]
they won't show up in markdown

**Comment by GusCaplan** [comment]
those checkboxes should be visible so we can verify they checked them

**Comment by GusCaplan** [comment]
additionally there is no point in having things markdown formatted if they will just be commented out

**Comment by GusCaplan** [comment]
your checkboxes are not valid markdown

**Comment by meew0** [comment]
Sorry, but we've had some discussions on Discord and decided to make our own one. Your help is still very much appreciated, of course; I took some inspiration from that when making this one – thanks for that!

**Pull request closed without merging**
