### PR TITLE
V8 es6

### PR DESCRIPTION
**Pull request by macdja38**
Reduce babel usage now that 0.12 has been discontinued
Fix typo receiving resume packet
Fix clearing of the cache on receiving a disconnect, because cache is used once resumed
Make sure heartbeats are being responded to
Misc webhook updates

### CODE REVIEW

**Comment by macdja38** [comment]
fails on v4 will fix tonight

**Comment by macdja38** [comment]
that should fix v4 support.

**Comment by GusCaplan** [comment]
Sweet jesus

**Comment by Gawdl3y** [comment]
I see no point in continuing maintenance of v8, and don't want to merge this. You can feel free to maintain your own fork. It is ultimately up to @hydrabolt, though.

**Comment by macdja38** [comment]
also fixes sending pms

**Comment by hydrabolt** [comment]
I no longer see the point in continuing support for v8 in the main repo, we _have_ already deprecated it. As @Gawdl3y said, it'd be cool to maintain this in your own fork 👍

**Comment by macdja38** [comment]
@hydrabolt in that case it would probably be best to delete the v8 branch and maybe link to my fork in the event anyone wants to use it... it can't maintain a connection to discord as the moment it attempt to resumes it sits there in a zombie state.

**Comment by GusCaplan** [comment]
i am against deleting the v8 fork as it contains the entire history of this lib up until v9

**Comment by macdja38** [comment]
@GusCaplan very good point

**Pull request closed without merging**
