### PR TITLE
update collectors

### PR DESCRIPTION
**Pull request by appellation**
**Please describe the changes this PR makes and why it should be merged:**
- better collector method names
- supports uncollecting

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
these names are worse imo

**Comment by appellation** [comment]
but they actually represent what the method does now

**Comment by appellation** [comment]
I have tested this and both existing types of collector appear to work.  However, I would definitely appreciate some extra testing from anyone who is willing.

**Comment by iCrawl** [comment]
Not liking the names either.

**Comment by appellation** [comment]
I'm open to suggestions. I renamed them because I needed consistent naming for removing collected elements, and those are the names that, to me, represent what those methods do. Since clearly more people disagree, please advise.

**Pull request merged**
