### PR TITLE
Http rewrite

### PR DESCRIPTION
**Pull request by Hackzzila**
This is basically the same as Gus' PR but with less total deps. I do need to fix up some webpack stuff

### CODE REVIEW

**Comment by GusCaplan** [comment]
it has the same number of deps 🙄

**Comment by iCrawl** [comment]
This should be tagged as WIP since its very incomplete yet.

**Comment by GusCaplan** [comment]
there are a number of issues with your http lib including your encoding check not being comprehensive, which will result in possibly gzipped/deflate/compressed data being passed through which will be bad

**Comment by Hackzzila** [comment]
Yes it is still a WIP, and besides super agent (which is being replaced) it uses less deps total

**Pull request closed without merging**
