### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by khionu**

### CODE REVIEW

**Comment by hydrabolt** [comment]
No point, the docs are already being rewritten with ESDoc in the ESDoc branch

**Comment by TehSeph** [comment]
Also, @khionu you're a contributor... just edit yourself. No need for a useless branch and PR.

**Comment by aequasi** [comment]
Should still PR for the sake of code reviews.

**Comment by khionu** [comment]
@TehSeph I was added as a collaborator for the sole purpose of helping review issues. I'm respecting that, and I am contributing as though I'm not a collaborator, even for things this minor.

**Comment by abalabahaha** [comment]
I'm fairly certain basic English syntax does not require a code review.

**Comment by TehSeph** [comment]
I just think for something minor like a spelling mistake it wouldn't matter. It's not like you're changing any code. And making a PR has just made a new branch in the repo that is completely useless now that this PR was declined. If you had just made the edit yourself in the original branch then it wouldn't have created a useless branch, useless PR, and the spelling mistake would have been corrected...

**Comment by khionu** [comment]
For future reference, if I notice any such discrepancies, or if something gets discussed in chat and it's regarding the docs, skip the PR?

**Comment by TehSeph** [comment]
I would personally say it should be at your digression. This edit was just the addition of a single character... Adding something more like say an entire paragraph you might still want to PR for.
Also, clone the repo and make your branch in your own cloned repo. The branch created for this PR was made in the official repo and looks out of place.

These are just my thoughts on the subject, and not representative of @hydrabolt's, @abalabahaha's, or @meew0's

**Comment by khionu** [comment]
Deleting the branch shouldn't delete this thread, right?

**Comment by TehSeph** [comment]
Nope. It won't.

**Comment by khionu** [comment]
I didn't think it would be an issue to open the branch for the fix then delete it again, but if that's bad practice, I will do as you recommend

**Comment by TehSeph** [comment]
Nah it wasn't bad. Just personal taste. Again, that's up to those guys.

**Pull request closed without merging**
