### PR TITLE
Guild.fetchMembers docs update

### PR DESCRIPTION
**Pull request by Tvde1**
**Please describe the changes this PR makes and why it should be merged:**
Added a line of documentation to `Guild.fetchMembers` that it returns a collection of new members.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [X] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
Line 504 already implies that.

**Comment by Tvde1** [comment]
I expected a collection of all members. This'll stop some confusion.

**Comment by iCrawl** [comment]
It should return a collection of all members tbh. Might as well fix the issue itself.

**Comment by Tvde1** [comment]
I thought this was intended oh

**Comment by bdistin** [comment]
Unneeded because of #1696

**Pull request closed without merging**
