### PR TITLE
Reconnect client option

### PR DESCRIPTION
**Pull request by Ratismal**
This pull request implements a ClientSetting labeled as `reconnect`, which is a boolean defaulting to `true`. When set to `true`, the client will automatically attempt to reconnect on an abnormal CloseEvent, and likewise when set to `false` it will stay disconnected. I'm not sure why this was removed, because this should be considered part of basic connection flow. Forcing reconnects on users isn't good.

As a personal example, I'm running a selfbot. Sometimes, for reasons I have not yet isolated, it gets into reconnect loops. These run for so long that my token ends up getting reset, because there's no form of limitation on reconnects.

I attempted to remedy this with the following code:

```js
reconnectAttempts = 0;
bot.on('reconnecting', () => {
    console.log('Reconnecting');
    if (++reconnectAttempts >= 10) {
        bot.destroy();
        alert(`Destroyed the bot after ${reconnectAttempts} reconnect attempts. Please manually reconnect.`);
    }
});
```

However, the client would continue to reconnect after being destroyed. 

I took this issue to the official discord.js support guild, where they told me to call `process.exit()`. This does not work because of my environment. Calling process.exit() would also kill everything else in the process; namely, my discord client itself. Since discord clients automatically reload, it would still be an endless reconnect loop.

I would greatly appreciate this being re-implemented as a workaround for `Client#destroy` not working. Thank you.

### CODE REVIEW

**Comment by GusCaplan** [comment]
all this does is let us turn off the functionality that is already in place.

**Comment by Ratismal** [comment]
Yes. I want to be able to turn off the functionality. That's the point of this PR.

**Comment by iCrawl** [comment]
If `client.destroy()` still reconnects it is a bug that should be fixed instead of monkey patching reconnect back in.

**Comment by Ratismal** [comment]
I still maintain that forcing reconnects on users is a bad practice. I merely gave a single case example, there are many others.

**Comment by iCrawl** [comment]
The decision to deny this PR is not my own, but I disagree. I don't see how having a bot not be online 24/7 is beneficial, these are supposed to be always available.

**Comment by Ratismal** [comment]
For a standard public bot, yes. It should be up 100% of the time.

However, you also have to take in account the people who use d.js for private bots and selfbots. For example, if someone is self-hosting a selfbot on a laptop and loses internet, the selfbot will continuously attempt to reconnect, which (while minimally) will cause performance drops.

My question is what justifies this options to be removed in the first place. Does the singular `this.client.options.reconnect` check on a ws close event cause ***so many issues*** that you had to completely nuke it? I honestly don't understand what the problem of implementing this is.

Unless you can specifically show me a negative to implementing this, I say it should be implemented. Even if it's used by one person, it's used.

**Comment by hydrabolt** [comment]
The reason that this was removed as an option in v9 is because I saw no scenario where a developer would realistically like their bot to not attempt to reconnect in case of any disconnections. I'm still open to adding it back as an option that's enabled by default, but I'm still struggling to see a real use case.

Until a decision has been reached, you can still listen for the `disconnect` or `reconnecting` events and call `client.destroy()` to prevent a reconnection.

**Pull request closed without merging**
