### PR TITLE
Add missing message to errors/Messages

### PR DESCRIPTION
**Pull request by xmatmen**
**Please describe the changes this PR makes and why it should be merged:**
This adds a missing message (Members didn't arrive in time) to the djsError class, fixing #1647

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
Probably would make more sense if it was FETCH_MEMBERS_TIMEOUT instead.

**Comment by Tvde1** [comment]
merge or homosexual

**Comment by xmatmen** [comment]
Looks like @hydrabolt already fixed this in c2a2cb29ac69eaf7693494451260c585913d93b5, but it's not merged yet

**Comment by Tvde1** [comment]
still homosexual if not merge

**Comment by xmatmen** [comment]
agree

**Comment by iCrawl** [comment]
Already committed on a different branch.

**Pull request closed without merging**
