### PR TITLE
Adding undefined checks to Server

### PR DESCRIPTION
**Pull request by aequasi**
Will at least prevent crashes

### CODE REVIEW

**Comment by khionu** [comment]
Personally, while I do acknowledge the Library's goal as to be as intuitive as possible..... I feel this is going too far. Checking for undefined is simple enough

**Comment by meew0** [comment]
Am I overlooking something or was this already done in 94f067cc51d39dc723f09aa16bf8e8886ce19703? If it was, why is there no conflict?

**Comment by khionu** [comment]
@meew0 lib versus src

**Comment by meew0** [comment]
@abalabahaha's change affected both though, this one only affected src

**Comment by abalabahaha** [comment]
I reverted undefined checks in favor of unavailable checks because it's bad to leave only parts of a server's data missing. I believe today's issue stems from unavailable servers not being handled correctly in the ready packet (pushed a fix).

**Pull request closed without merging**
