### PR TITLE
add new fetchers to client

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by Gawdl3y** [comment]
Should definitely have the option to not cache the object, as you said.

**Comment by Gawdl3y** [comment]
The default for `fetchChannel` and `fetchGuild` should probably be `false`, as them being in the cache may mislead into believing the library is fully handling everything for them, when that is definitely not the case.

**Comment by hydrabolt** [comment]
When would it ever be necessary to fetch a channel or a guild?

**Comment by GusCaplan** [comment]
useful in sharding, that is about it

**Comment by hydrabolt** [comment]
wouldn't return channels, roles or members, maybe that should be made clear in the docs

**Comment by GusCaplan** [comment]
this could be replaced with the @hydrabolt's static methods idea.

**Pull request closed without merging**
