### PR TITLE
Client.addMemberToRoles is now functional

### PR DESCRIPTION
**Pull request by ChrisTalman**
Also prevents duplicate roles being added to users.

### CODE REVIEW

**Comment by meew0** [comment]
It looks like the fix is only on the compiled (lib/) directory, could you also commit the respective src/ directory so it doesn't get overwritten in the next recompile?

**Comment by abalabahaha** [comment]
Wrong branch :/

**Comment by meew0** [comment]
Do you even cherry-pick?

**Comment by abalabahaha** [comment]
oh wrong commit ID, updated comment

**Pull request closed without merging**
