### PR TITLE
Fixed DataStore, deprecation leftovers and a bit of Event Constants

### LINKED ISSUE #1838: The method "bulkDelete" on TextChannel, when using a number tries to use the "fetchMessages" method which no longer exists.
**Please describe the problem you are having in as much detail as possible:**
When using the bulkDelete method with a number it fails because it tries to use the fetchMessages method which was deleted in the latest commit. [Here](https://github.com/hydrabolt/discord.js/blob/master/src/structures/interfaces/TextBasedChannel.js#L281)
This is because of MessageStore existing where you can do more things so 
```js
channel.messages.fetch({ limit: messages })
```
Should be used

**Include a reproducible code sample here, if possible:**
```js
msg.channel.bulkDelete(50).catch(console.error);
```

**Further details:**

- discord.js version: 12
- node.js version: 8.1.2
- Operating system: Debian 8 Server
- Priority this issue should have – please be realistic and elaborate if possible:
Moderate. A big issue to anyone who has a purge command and is on master

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #1838 
- Replaced hopefully all `fetchUser`s and `fetchMessages` (couldn't find anything else) whith their respective Datastore method.
- Removed unused error messages.
- Removed no longer existing methods from Channel classes.
- Added `RESUMED` event constant
Also changed `Client#resume` to `Client#resumed` as that was a typo.
- Used event constants everywhere possible over hardcoded strings.
- Replaced mention ot `createCollector` with `createMessageCollector` as that method name was deprecated and already removed.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by MinecraftBoxGuy** [comment]
Please merge this soon

**Comment by Dev-Yukine** [comment]
well you know thats not how PRs work they must be confirmed/reviewed by someone and if you need that you can run your bot with the d.js version from this PRs commits 🤔

**Comment by devsnek** [comment]
i dunno what `RESUME` is , it should be `RESUMED`

**Comment by SpaceEEC** [comment]
It's currently `resume` as you can see [here](https://github.com/hydrabolt/discord.js/blob/ac92d2cecc654f3614321022d5c377bf0bc60f4b/src/client/websocket/packets/handlers/Resumed.js#L17), so I went with `RESUMED` as event constant.

**Pull request merged**
