### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by xdamman**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/discord.js ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
  
  You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets
  
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. [[More info](https://github.com/OpenCollective/opencollective-cli)]

### CODE REVIEW

**Comment by hydrabolt** [comment]
sorry decided against joining the open collective

**Comment by xdamman** [comment]
Ah. Ok. Can I ask why?

**Comment by hydrabolt** [comment]
@xdamman sorry, going to reconsider this and check again in the morning!

**Comment by devsnek** [comment]
downdoot imo

**Comment by xdamman** [comment]
Thanks for the feedback. 

FYI this pull request is not all or nothing. You don't have to have the postinstall or the message in the issue template. That's really up to you (we should make that more clear). The only thing "required" is the placeholders on the readme because it's important to acknowledge backers/sponsors.

**Comment by hydrabolt** [comment]
Hi @xdamman. Thank you for making this PR, but I'm afraid we've decided against joining the open collective - it just doesn't fit the nature of our project.

**Comment by xdamman** [comment]
That's ok. I understand. No worries. Hope to see you again if not for this project for another one in the future :-)

**Comment by hydrabolt** [comment]
Thank you @xdamman 😄

**Comment by boneskull** [comment]
**Please don't take this as criticism.**  I'm not trying to change anybody's mind.  I'm a bystander (who happens to contribute to a project with [a collective](https://opencollective.com/mochajs)) who is curious about some of the comments here.

To @meew0 and @iCrawl in particular,

- I'm wondering about why joining OC would label the project or contributors as "sellouts"?  
- How would it tarnish the reputation of the project?   

If there's a feeling that accepting donations is a bad idea, it would be helpful for other projects to understand *why*.

**Comment by devsnek** [comment]
- joining the collective kinda says we're actively looking for money, *which we aren't*
- to the above, if we don't need money, why would we ask for it? (makes us look greedy)

**Comment by xdamman** [comment]
Many developers don't need money.
So I personally see this more as a way to enable people who cannot contribute code but would love to contribute financially to have a place to do so (in a transparent way). And then that money can be used to enable the community to meet, or to invest in things that will make it easier for new people to learn and contribute. While you may not personally need the money, you may not want to spend your own money for those expenses.

That said, this is not for all open source projects. I think it works best for the ones that have an active online community that wants to put money together to sustain their community.

Again, no worries. And thank you for sharing your feedback. It's always useful!

**Comment by iCrawl** [comment]
@boneskull I don't feel like its a bad thing in *general*, don't get me wrong. I'm all up for people donating and supporting a piece of software they use, by all means.
But on the other hand you just have to take the community you develop this for /develop this in into account. I don't wanna delve too much into it, but what I essentially meant with tarnish was that once you go down that path and realize it maybe wasn't the best move, getting out of there is going to be way harder.

So no, I def. don't want to say its bad, rather it doesn't fit with the discord.js project and the community we develop this for.

**Pull request closed without merging**
