### PR TITLE
Reasons

### PR DESCRIPTION
**Pull request by PgBiel**
**Please describe the changes this PR makes and why it should be merged:**
Basically adding reasons to probably everything possible. Please tell me if I missed something or mistakenly added reason to something that can't have it.
(About GuildMember reasons, those are in #1710)

**Semantic versioning classification:**  
- [X] This PR changes the library's interface (methods or parameters added)
- [X] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
i kinda left out the ones that call .edit on purpose but ¯\_(ツ)_/¯

**Comment by KingDGrizzle** [comment]
Emoji#setName :P

**Comment by KingDGrizzle** [comment]
Should TextChannel#clone also get reasons, or is it not needed?

**Comment by PgBiel** [comment]
@KingDGrizzle check GuildChannel

**Comment by devsnek** [comment]
just give me a reason just a little bit's enough 🎵

**Pull request merged**
