### PR TITLE
Guild.memberCount should be changed internally

### PR DESCRIPTION
**Pull request by Programmix**

### CODE REVIEW

**Comment by Gawdl3y** [comment]
Won't this break `Guild.fetchMembers`? It seems to rely on `memberCount` not changing when adding members through that.

**Comment by Gawdl3y** [comment]
`Guild.fetchMember` probably needs to increment `memberCount`, though.

**Comment by Programmix** [comment]
It seems to me that `Guild.fetchMembers` relies on the same methods modified here. Unsure, but as far as I can tell, `Guild.fetchMembers` should still work normally.

**Comment by Gawdl3y** [comment]
`Guild.fetchMembers` relies on `memberCount` not changing, and the websocket handler for the guild chunks calls `_addMember`. This would definitely break `fetchMembers`. I'm not sure whether `fetchMember` should increment or not, either.

**Comment by hydrabolt** [comment]
It's not done internally because some internal methods also run `guild._addMember` without the websocket event, memberCount should only be updated from the packet itself.

**Pull request closed without merging**
