### PR TITLE
Update the greeting a tiny bit.

### PR DESCRIPTION
**Pull request by AlexHGaming**
**Please describe the changes this PR makes and why it should be merged:**

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by AlexHGaming** [comment]
I am new to this type of repo so don't expect me to know how the repo works, I've seen the latest PR's so I'm like why not do this _insert shrug face here_

**Comment by Gawdl3y** [comment]
That's actually worse grammar, as a comma is not optional in that spot. I'm also not really a fan of prefixing it with "New Member!"

**Comment by AlexHGaming** [comment]
Ok I will remove new member.

**Comment by iCrawl** [comment]
Changing `discord.js` to `Discord.JS` isn't any better. We don't use that kind of capitalization anywhere, it's always `discord.js`.

So essentially, I'm not sure if any of that is needed. The Guild suffix in the first sentence is kind of implied since your normal bot does not act in a GroupDM.

**Comment by AlexHGaming** [comment]
Alright, I feel like this isn't needed.
Closing;

**Pull request closed without merging**
