### PR TITLE
Remove .end and default to .destroy

### PR DESCRIPTION
**Pull request by FireController1847**
**Please describe the changes this PR makes and why it should be merged:**
It seems kind of unnecessary to create a custom .end, when you could easily default it to destroy without having to have the extra method. Would be easy cleanup and looks a lot better.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aemino** [comment]
I don't see the point of this. The method was supposed to be `StreamDispatcher.end()`. Yes, it's a bit of a redundant method, but the purpose was semantics, and imo, `end` is the winner in terms of what feels better.

**Comment by FireController1847** [comment]
The name of a method has never stopped you guys before, it was always about
the cleanslness of the code. I find it interesting I find one redundant
function and this is the one that shouldn't be changed.

**Comment by appellation** [comment]
Since `destroy` was previously undocumented, basically the only thing you've done is rename the `end` method and made it more complex.  I think that the added complexity is useless.  The only way this becomes slightly valid (in my opinion) is if all available destroy types were documented, which I think is a bad idea since many of them should not be used externally.

Essentially, this adds useless complexity.

**Comment by FireController1847** [comment]
I don't understand how this is more complex? Each of the variables are
optional, and it makes more sense to destroy a dispatcher than end it.  Of
course, we wouldn't have to document destroy for everything as in a lot of
cases there is a big difference between end and destroy, but for the
dispather there is absolutely no difference.

**Comment by appellation** [comment]
`.end('dank memes')` vs `.destroy({ reason: 'dank memes' })` is admittedly not a huge deal, but it does address the unnecessary complexity I was addressing.  Plus the added effort of refactoring my code for an breaking change that does pretty much nothing.

**Comment by FireController1847** [comment]
It cleans up the code and makes more sense, that the entire reason I added
it. I use this music feature a LOT, and if I didn't feel this PR was good
enough to make I wouldn't have, but it just seemed like it needed it.

**Comment by FireController1847** [comment]
Sorry if that sounded a little passive agressive I'm trying to be sincere but my text doesn't really show that.

**Comment by appellation** [comment]
I'm aware that you think this PR is worthwhile, since people rarely PR stuff they think is useless.  I'm merely expressing my opinion that it is useless, and why.

**Comment by FireController1847** [comment]
Yeah, alright.

**Comment by iCrawl** [comment]
aemino gave a pretty good comment on why this is the case and we are probably not going to change it.

Apart from that he is also working on a rewrite for v12 targeting the Audio section.

**Comment by FireController1847** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
