### PR TITLE
RichEmbed setField method

### PR DESCRIPTION
**Pull request by xDdude**
**Please describe the changes this PR makes and why it should be merged:**
Not gonna delete fork this time. This is a convenience method for changing properties of a rich embed field after it has been added, it's quite useful for those who use the rich embed builder as it lets them edit their original embed fields in the similar style to the way they added them. To reduce code duplication there is a new method `_validateField` that just checks all the properties of the fields being added/changed.

There are many ways to implement this but I thought this fit in with the rest of the class.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
- [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
Is there any reason to keep _validateField public? You could make it a function at the bottom like resolveString...

**Comment by xDdude** [comment]
I mean I gave it the typical fake privacy, but I can change that I guess. Tbh i don't know why resolveString is down there in the first place, that function just brings undesired output and avoids errors, not to mention that it's just a duplicate from the ClientDataResolver that hasn't been converted to a static method rather its just been duplicated (unlike resolveColor).

**Comment by iCrawl** [comment]
Doesn't seem like a bad idea, but it comes down to how much code you really spend on writing and how convenient it is.

Consider this to change the first field inline to false:
```js
embed.setField(0, null, null, false);
```

While in comparison you could just do
```js
embed.fields[0].inline = false;
```

**Comment by xDdude** [comment]
I agree, I don't actually use the RichEmbed class I just saw some people kinda struggling with the idea that they could change the properties of it so I decided to make this. Tbh I figured most people would just redundantly type out everything again, which would be a lot more newbie friendly.
```js
embed.addField("title", "value", true);
embed.setField(0, "title", "value", false);
```
That was the whole goal of this pr, a lot of people who are new to the lib are generally new to javascript as well and are then encouraged to use this class because its "easier", this kind of leads to issues where they think a rich embed instance is completely different to the object literal alternative, hence they don't realise you can use something like `embed.fields[0].inline = false;`.

The only other alternative to this is adding like 3 more methods for this method that changes each field on there like `embed.setFieldInline` etc, though that might make the class a bit bulky for a small benefit.

**Comment by bdistin** [comment]
I have also thought about a embed.spliceField which would allow you to insert a new field and or delete any number of fields at a given index. Given the nature of your method, it would make more sense to call it embed.editField even though it is one char longer. Setting a field with nulls tends to lead the idea that you would actually set to null, rather than ignoring that particular value. Where as editing, gives the impression that null would be an ignored argument.

**Comment by xDdude** [comment]
Yeah i can see how that the whoe null thing would cause confusion. Something like splice field sounds interesting but then again its kinda like, why wouldn't you just use array.splice on the embed fields and it kinda doesnt fit in well.

I might change this a little bit tomorrow but I still think something like this should be added.

**Comment by bdistin** [comment]
My idea with splice field, is you could have a cached constant template embed, and you could splice in the changing values where it needs to go. Right now if you exclusively use the builder, you must add them in order.

**Comment by xDdude** [comment]
Maybe someone else can implement this better...

**Pull request closed without merging**
