### PR TITLE
Migrate from snekfetch to phin

### PR DESCRIPTION
**Pull request by ethanent**
**Please describe the changes this PR makes and why it should be merged:**

This PR proposes switching from the snekfetch HTTP client library to the phin library. The purpose of this change is to reduce weight of the overall discord.js library. phin is **90% smaller** than the snekfetch library. (10KB vs 107KB)

This PR improves discord.js install time significantly by reducing dependency tree size.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Dev-Yukine** [comment]
even tho snekfetch might not be as small as phin i dont think d.js will move away from snekfetch for several reasons, one might be that snekfetch is made by Gus who is one of the core developer of d.js. also beside that you completly ignore the eslint configuration of this projects thats why your build is failing in travis.

**Comment by ethanent** [comment]
Thanks, @Dev-Yukine. I went ahead and ran the lint, build is passing now.

I'm sorry to hear that the d.js team may be biased, but I'll try my best to push for this positive change to the library!

**Comment by Dev-Yukine** [comment]
well seems like they might think about change to your libary 😅

**Comment by 1Computer1** [comment]
Have you tested this to make sure things work? Especially file sending and such.

**Comment by TrueBoxGuy** [comment]
I don't understand how this improves discord.js install time significantly as discord.js master is already at about 37mb and this would only make a 90kb difference. Is this really worth it when Gus will be able to fix any problems djs has with his library and is a big collaborator of djs. Development will be easier for djs with someone who knows how to use its HTTP library fully.

**Comment by TrueBoxGuy** [comment]
Does a couple seconds of install time really matter though, compared to having someone who knows how to use the http request library very well and add things to his library to work with djs.

**Comment by ethanent** [comment]
@TrueBoxGuy According to a benchmark by @Dev-Yukine, phin is >~60% faster at sending individual requests than snekfetch.

image

**Comment by iCrawl** [comment]
This needs **way** more comprehensive testing than just:
>ran the lint, build is passing now

Some things that come to mind:
- sending images
- sending files
- sharding
- webpack compat
- browser support in general

**Comment by TrueBoxGuy** [comment]
@ethanent 
image
It is surely faster, but it is hard to get an exact result as internet speed can vary a lot. This method of benchmarking is inaccurate, you may need to limit the speed to something you will always get. However that still doesn't show how much faster the lib is because a lot of the time is from how long it takes to download the resource, this does not actually show the speed of the code from the library. Also, both of them are extremely fast. Is the change worth it for a tiny bit more speed?

However, I like how elegant and small your lib is and think you have done an amazing job with it. I am just not sure if it is suitable for djs. Keep up the good work 👍 !

**Comment by ethanent** [comment]
Totally agree, @iCrawl. Note that there are some errors currently. I'm still testing the PR in-depth with @bdsomer.

**Comment by ethanent** [comment]
Thanks, @TrueBoxGuy! I definitely see what you mean. Replacing snekfetch in discord.js is very complex. 😄

**Comment by devsnek** [comment]
phin doesn't fulfill our goals of browser comparability, and it lacks a great number of features compared to snekfetch. aside from that if some actual code for sending request timing could be shown that would be fantastic because 74ms and 89ms are both astronomically high numbers for http request engines (when testing snekfetch i try to stay below 30ms for rtt to a nearby cloudflare edge server)

**Comment by ethanent** [comment]
Good point. Browser compatibility would be an issue with phin. I'll be closing this PR (at least for now) as phin likely isn't the right fit for discord.js currently.

**Pull request closed without merging**
