### PR TITLE
add lru to collections

### PR DESCRIPTION
**Pull request by devsnek**
**Please describe the changes this PR makes and why it should be merged:**
we need LRU for bot dms (hammerandchisel/discord-api-docs/issues/184)

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by hydrabolt** [comment]
I think this only really needs to be added to the channel data store

**Comment by CharlotteDunois** [comment]
Honestly, the loop in `lru.add` can be replaced by `lru.splice(0, options.lru`. If possible, adding any usage-specific features for a general-purpose class should be avoided.

**Comment by devsnek** [comment]
@CharlotteDunois i mean this in the nicest way, but you're an idiot.

**Comment by CharlotteDunois** [comment]
@devsnek Do you always get unnecessarily rude? Pretty immature.

**Pull request closed without merging**
