### PR TITLE
ws compression is cool

### PR DESCRIPTION
**Pull request by devsnek**
**Please describe the changes this PR makes and why it should be merged:**
- implements this crazy fast and low bandwidth zlib thingy that jake sold to me in the back alley last night

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by hydrabolt** [comment]
image

**Comment by aemino** [comment]
✅ plagiarized @qeled's code
✅ using a the wrong package name `zlib-stream` isn't owned by abalabahaha at the moment
✅ this pull request dealing with a serious issue is basically a meme

**Comment by abalabahaha** [comment]
:white_check_mark: forecasting the right package name as zlib-sync is owned by abalabahaha at the moment

**Pull request merged**
