### PR TITLE
Replace {null} in JSDocs with {void}

### PR DESCRIPTION
**Pull request by Gawdl3y**
These functions are not returning `null`. They are returning nothing, so `{void}` is more appropriate.

### CODE REVIEW

**Comment by Hyper-Coder** [comment]
The literal term for nothing in JS is null. Why put void? You don't do `const variable = void`

**Comment by Gawdl3y** [comment]
Those functions are not returning `null`, they are returning literally nothing. They technically return `undefined`. The usual convention for JSDoc is to use `{void}` to indicate that. ESLint even detects `{void}` so that you don't have to provide a description for it, if you're using the `requireReturn` part of the `valid-jsdoc` rule.

**Comment by Hyper-Coder** [comment]
Ah, I see now.

**Comment by Gawdl3y** [comment]
The docs stating that these methods returning `null` is misleading, as if you were to (for some reason) test `someMethod() === null`, you would always get `false`.

**Comment by Gawdl3y** [comment]
#582 supersedes this PR.

**Pull request closed without merging**
