### PR TITLE
docs: add Guild#features type

### PR DESCRIPTION
**Pull request by Lewdcario**
**Please describe the changes this PR makes and why it should be merged:**
Guild#features was abstract/not very obvious so I added typings for it, which I feel is necessary because it can only be a specific subset of strings in an array.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
Why does this need an entire typedef? I'd be interested in minimizing extra documentation that has limited purpose; I think just putting it in the existing doc string is sufficient.

**Comment by Lewdcario** [comment]
We have other typedefs for types used just once - so I thought this was alright, I'm not sure what'd be preferred, though.

**Comment by appellation** [comment]
Fair enough. I still disagree with the concept, but consistency is good. 👍

**Comment by ThaTiemsz** [comment]
Misses `MORE_EMOJI`

**Pull request merged**
