### PR TITLE
Overhauled most of the types. Added missing methods and properties. I also reordered properties alphabetically where it wasn't the case

### PR DESCRIPTION
**Pull request by MichaelBeier**

### CODE REVIEW

**Comment by iCrawl** [comment]
cc/ @zajrik

**Comment by zajrik** [comment]
I'll be reviewing this over the course of the evening. 👌

**Comment by zajrik** [comment]
Alright, here's the deal. I've come across a crapload of additions that need to be made in my review, and a couple changes in your PR that need to be made. I don't want to dump all the additions that need to be made on your lap so I'm going to take your changes and make the necessary additions myself. I'll credit you in the PR.

In the future, please make pull requests for typings to [acdenisSK/discord.js-typings](https://github.com/acdenisSK/discord.js-typings) where we have the proper tooling for linting and testing for the typings, and denis and myself have more control over additions prior to actual PRs into d.js proper.

**Comment by MichaelBeier** [comment]
Alright, noted. Feel free to hit me up, in case you need help.

**Comment by zajrik** [comment]
Alrighty. And thank you again for initiating this. I've been meaning to get started on bringing the typings up to date for release but this finally got me off my butt to do it.

**Pull request closed without merging**
