### PR TITLE
OCD ;)

### PR DESCRIPTION
**Pull request by JacobGunther12**
**Please describe the changes this PR makes and why it should be merged:**
A simple change to the README that capitalizes a letter.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [X] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
as long as you're changing this, we support node.js and browser. Additionally, we have a PR template which you appear to have deleted

**Comment by JacobGunther12** [comment]
I believe that this was such a small change, that it didn't need a template. All I did was capitalize a single letter.

**Comment by devsnek** [comment]
then you would check the box `This PR only includes non-code changes, like changes to documentation, README, etc.`

**Comment by JacobGunther12** [comment]
Updated

**Comment by hydrabolt** [comment]
Maybe add a note about it being able to be browserified as @devsnek suggested?

**Pull request closed without merging**
