### PR TITLE
make lib better

### PR DESCRIPTION
**Pull request by GetRektByMe**

### CODE REVIEW

**Comment by iCrawl** [comment]
🤔

**Comment by GetRektByMe** [comment]
This should be merged asap @foxbot otherwise the lib won't be able to cope w/ new changes to the API.

**Comment by Programmix** [comment]
I don't understand these changes; this seems to make the API much worse.
Could you please elaborate?

**Comment by hydrabolt** [comment]
bye

**Comment by GetRektByMe** [comment]
Why would you do this Hydra :( I worked so hard

**Pull request closed without merging**
