### PR TITLE
Remove default channel resolving from guild input.

### PR DESCRIPTION
**Pull request by KyeNormanGill**
**Please describe the changes this PR makes and why it should be merged:**
Removes guild as a possible parameter from resolveChannelID as default channels aren't in the API anymore (or won't be) idk.

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
Just FYI, this probably won't get merged because the data manager is removed in #1618.

**Comment by appellation** [comment]
Oh, resolver not manager.  mb

**Comment by KyeNormanGill** [comment]
[cries in spanish]

**Comment by hydrabolt** [comment]
sorry this has already been done in another commit where I removed loads of other resolve crap!

**Pull request closed without merging**
