### PR TITLE
Add FEC and PLP support for Opus encoding

### PR DESCRIPTION
**Pull request by aemino**
Enables FEC (forward error correction) and PLP (expected packet loss percentage) settings for Opus encoding.

See Jake's PR to discord.py that adds this:
https://github.com/Rapptz/discord.py/commit/7efabce4b2a1ddc0193f9d544cd90185d4740042

### CODE REVIEW

**Comment by Programmix** [comment]
This shouldn't be merged until https://github.com/Rantanen/node-opus/pull/28 is merged; otherwise this PR will not work.

**Comment by Programmix** [comment]
Also, open for discussion:
How should lack of support for CTL flags be handled? (meaning the engine being used is out of date)

**Comment by GusCaplan** [comment]
do a silent check for the exposed method, if they don't have it, just don't do anything

**Comment by Programmix** [comment]
I suppose I'll just try/catch and ignore if an error is thrown.

**Comment by Rantanen** [comment]
Sorry for this. @aemino's pull request had passed me by somehow.

Reviewed it now and merged in. Will publish a new version of node-opus.

**Comment by iCrawl** [comment]
@Rantanen thank you very much! 👍

**Pull request merged**
