### PR TITLE
"knock, knock. who's there. discord, lol"

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by hydrabolt** [comment]
I'm not even renaming this it is brilliant

**Comment by meew0** [comment]
The handling for this is slightly wrong, a received heartbeat should be answered with a sent heartbeat, not with a heartbeat ack - sending a heartbeat ack at any time will immediately cause a 4001 (unknown opcode) disconnect. (Did you not test this code? :P)

**Comment by hydrabolt** [comment]
Welp will change later

**Comment by GusCaplan** [comment]
@meew0 and anyone else interested, fixed in #1023

**Pull request merged**
