### PR TITLE
Add sendCode() to channels (#625).

### PR DESCRIPTION
**Pull request by hkwu**
Not sure if `Message` should get `replyCode()` as well.

### CODE REVIEW

**Comment by Gawdl3y** [comment]
This won't play nicely with splitting at max message length. I incorporated [a helper method](https://github.com/Gawdl3y/discord-graf/blob/master/src/bot/util.js#L200) in GRAF that could be useful for doing this nicely. Perhaps such a helper belongs in discord.js?

**Comment by hkwu** [comment]
How's this?

```js
const MESSAGE_CHAR_LIMIT = 2000;

const splitString = (string, prepend = '', append = '') => {
  if (string.length <= MESSAGE_CHAR_LIMIT) {
    return [string];
  }

  const splitIndex = string.lastIndexOf('\n', MESSAGE_CHAR_LIMIT - prepend.length - append.length);
  const sliceEnd = splitIndex > 0 ? splitIndex : MESSAGE_CHAR_LIMIT - prepend.length - append.length;
  const rest = splitString(string.slice(sliceEnd), prepend, append);

  return [`${string.slice(0, sliceEnd)}${append}`, `${prepend}${rest[0]}`, ...rest.slice(1)];
};
```

It *should* have mostly the same functionality as your helper, just didn't want to copy everything lol.

**Comment by Programmix** [comment]
I don't think a method like this belongs in the lib. If you have a use for this, make a helper library and use it yourself! :D

**Comment by Tyler0130** [comment]
While I disagree with @Hyper-Coder that there is no use for this at all, I do agree with @Programmix in that you can easily create a function for this yourself and isn't something that's necessary for the library.

**Comment by hkwu** [comment]
The method is pretty redundant, though we have `sendTTSMessage()` as well, so idk. Gonna close it then.

**Comment by Meowbeast** [comment]
Well, this was a feature I discussed with @hydrabolt and he asked me to put a ticket in for...glad to see it was open for discussion before being closed.  Classy.

**Comment by hkwu** [comment]
@Meowbeast didn't know that, so is it confirmed that this should be added or not?

**Comment by Meowbeast** [comment]
It's not confirmed...it was up for discussion.  Along the same lines as allowing .sendMessage to take Arrays.  It's not needed...but for all the times people send code blocks and have to format their code funky to allow for ticks and MD...it wouldbe a handy feature to have.  Something other libs don't have that would make the lib a little more user-friendly.

There's always an argument for "no, it's not needed, you can code it yourself", sure.  Just like you could code collections yourself.  I thought it would be handy feature to have and allow for cleaner coding out of the box. 

My intention was to try and PR this myself...but I'm not ninja enough for that ATM.

Go ahead and close it.  I see the path we are heading when it comes to feature requests.

**Pull request closed without merging**
