### PR TITLE
Some Changes to the Redme.

### PR DESCRIPTION
**Pull request by AraHaan**

### CODE REVIEW

**Comment by meew0** [comment]
Could you add some text about what's for what purpose? Something like  
"master: More stable"  
"indev: Latest features"

**Comment by hydrabolt** [comment]
Master isn't npm...

**Comment by abalabahaha** [comment]
It would be preferrable to not tell regular users to depend on indev...

**Comment by meew0** [comment]
Why not? We regularly tell users to use it for specific problems and if they need specific features. There's no reason not to include it in the readme as long as we note that it's unstable.

**Comment by meew0** [comment]
Alternatively we could make more frequent development releases - but I definitely think we should have some way for users to use bleeding-edge code.

**Comment by hydrabolt** [comment]
If they really want to use bleeding edge surely they'd already know how to install from indev

**Comment by abalabahaha** [comment]
Not everyone reads before blindly installing stuff

**Pull request closed without merging**
