### PR TITLE
Change url to the other Discord API libraries.

### PR DESCRIPTION
**Pull request by alfw**

### CODE REVIEW

**Comment by GexoXYZ** [comment]
I approve because the old one just returns a 404

**Comment by meew0** [comment]
This is probably not intended though, @abalabahaha please fix the 404

**Comment by TehSeph** [comment]
The old link was better imo. Just a matter of it 404ing right now. :S

**Comment by abalabahaha** [comment]
Yeah I'll do this when I can, forgot ot test my nginx config :/

**Pull request closed without merging**
