### PR TITLE
Added info about Discord Nitro

### PR DESCRIPTION
**Pull request by LasseNiermann**
**Please describe the changes this PR makes and why it should be merged:**
Only a little hint that Discord Premium means Discord Nitro.
It isn't very clear for non-discord-nerds

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
We don't accept PRs to the stable branch.

**Comment by LasseNiermann** [comment]
Sorry. Just fixed it. Is it right now?

**Comment by iCrawl** [comment]
Do you think? 😃 

You'll have to rebase the branch.

**Comment by LasseNiermann** [comment]
Okay... sorry... I am a noob

**Pull request closed without merging**
