### PR TITLE
Add Guild.defaultChannel.

### PR DESCRIPTION
**Pull request by hkwu**

### CODE REVIEW

**Comment by Programmix** [comment]
Really makes no practical difference but I feel like a property like this should be a `getter` rather than a property of the class.

**Comment by Gawdl3y** [comment]
I agree with @Programmix. It should definitely be a getter. Additionally, the docs need to be rebuilt. :eyes:

**Comment by Meowbeast** [comment]
Hmm, is this really needed?  Can't we just do `guild.channesl.get(guild.id)`?

**Comment by Gawdl3y** [comment]
This is a nice shortcut, and hides away the detail of default channels having the ID of the guild.

**Pull request merged**
