### PR TITLE
fix voice state updates

### PR DESCRIPTION
**Pull request by macdja38**
Should fix https://github.com/hydrabolt/discord.js/issues/430
Issue was .has() has specific meaning for the cach, while .includes() will check if the cach contains the user

### CODE REVIEW

**Comment by abalabahaha** [comment]
Node 0.12 does not have Array.includes(), and Babel doesn't appear to be polyfilling it

**Comment by winneon** [comment]
discord.js doesn't appear to be using the es2015 babel preset. Is there is a reason for this? `Array#includes()` should be polyfilled if you're using that preset.

**Comment by winneon** [comment]
Okay, discord.js is so far up CommonJS's ass that trying to convert it to babel's es2015 preset is a nightmare. Instead, how about [this solution](https://github.com/stoeffel/babel-plugin-array-includes)?

**Comment by abalabahaha** [comment]
Or, we could not rely on Babel, and instead do what that plugin's description says (Replaces `arr.includes(val)' with `arr.indexOf(val) >= 0`)

**Comment by winneon** [comment]
You *could* do that, but then you'll miss out on all the ES6 sexiness!

**Pull request merged**
