### PR TITLE
Add super properties and context properties

### PR DESCRIPTION
**Pull request by Vap0r1ze**
This will prevent user accounts from being unverified when using certain methodsa

### CODE REVIEW

**Comment by iCrawl** [comment]
A-any more explanation on that?

Also your build is failing btw.

**Comment by Vap0r1ze** [comment]
I haven't even finished it

**Comment by Vap0r1ze** [comment]
This is why you shouldn't code within 20 minutes of waking up

**Comment by GusCaplan** [comment]
we aren't actually allowed to merge this anyway lol

**Pull request closed without merging**
